# These are supported funding model platforms
github: ptprashanttripathi 
patreon: ptprashanttripathi
open_collective: ptprashanttripathi
ko_fi: ptprashanttripathi
custom: ['https://www.paypal.me/ptprashanttripathi']
